# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DailyUpliftNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for DailyUpliftNative

  target 'DailyUpliftNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyUpliftNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

